### 보드 등록
GET http://localhost:6296/board/save
Content-Type: application/json

{
  "title": "sangNamJa",
  "content": "Cho Young-In"
}

### 보드 탐색
GET http://localhost:6296/board/findAll
Content-Type: application/json

### 보드 업데이트
PUT http://localhost:6296/board/update
Content-Type: application/json

{
  "title": "sangNamJa",
  "content": "Chooo Young-In"
}

### 보드 삭제
DELETE http://localhost:6296/board/delete/{title}
Content-Type: application/json
