server:
  port: 6296

spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  properties:
    hibernate:
      format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/board
    username: sa
    password:
